name: Laravel Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:

    - name: Deploy To Server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd /var/www/laravel-app

          git pull origin main

          composer install --no-dev --optimize-autoloader

          php artisan migrate --force

          php artisan optimize:clear

          php artisan config:cache

          php artisan route:cache

          php artisan view:cache
